### ISSUE TITLE
Support for nvidia runtime

### ISSUE THREAD

**Issue by AlpinDale** [NilsIrl/dockerc#25] opened 2024-08-05 16:14 UTC
I'd like to assist in adding support for the NVIDIA runtime, as we're currently unable to use any Docker images that utilize CUDA. Could you provide some pointers on where to begin?

**Comment by tmm1** [comment] 2024-08-05 16:28
Dupe of #15 prolly

**Comment by NilsIrl** [comment] 2024-08-05 19:27
Duplicate of #15. Will answer the question there.

**Closed as not planned** 2024-08-05 19:27 UTC
