### ISSUE TITLE
chown `/dev/pts/0`: Invalid argument

### ISSUE THREAD

**Issue by gander** [NilsIrl/dockerc#13] opened 2024-03-08 12:53 UTC
What is wrong?

```shell
dockerc --image docker://gander/dev:8.3 --output gander-dev
./gander-dev
```

```
2024-03-08T12:50:46.663596Z: chown `/dev/pts/0`: Invalid argument
```

**Comment by NilsIrl** [comment] 2024-03-08 20:16
I'm currently investigating this issue.

Duplicate of #6

**Closed as not planned** 2024-03-08 20:51 UTC
