### ISSUE TITLE
Changing ownership of 'file_names': Operation not permitted

### ISSUE THREAD

**Issue by MichalisDBA** [NilsIrl/dockerc#10] opened 2024-03-07 09:48 UTC
When i try to run the binary file i get these errors.

Tried with `--rootfull` too same problem.

`chown: changing ownership of '<file_names>': Operation not permitted`

**Comment by NilsIrl** [comment] 2024-03-07 09:50
Duplicate of #6

**Closed as completed by NilsIrl** 2024-03-07 09:50 UTC
